### ISSUE TITLE
logo is broken

### ISSUE THREAD

**Issue by messense** [napi-rs/website#24]
<img width="512" alt="CleanShot 2022-02-04 at 11 03 28@2x" src="https://user-images.githubusercontent.com/1556054/152465348-05e48ec9-58a0-402f-a1c9-c3205350df37.png">

https://napi.rs/static/logo-with-text-ccd3d229793ec446a7dbb97ea3211a2a.png

**Comment by Brooooooklyn** [comment]
@messense seems like your browser cached the old version of the website. Try to uninstall the `sw.js` in the PWA section of devtool.

**Comment by messense** [comment]
It works, thanks! But it's kinda odd to have to do that to make it work though.
